# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/neoadmin
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: cat package.json
      - run: npm run-script test
